@startmindmap
* Teamup Ventures
** Home - 340B Price Guide (/)
*** Form: post /
**** Field: searchword (text)
**** Button: Go
*** Form: post /
**** Field: username (text)
**** Field: password (password)
**** Field: remember (checkbox)
**** Field: Submit (submit)
**** Field: Submit (submit)
**** Button: Log in
**** Button: Sign up / i’m New
*** Form: GET 
**** Field: searchword (text)
**** Button: FIND 340B PRICES
*** Articles and News - 340B Price Guide (/index.php/articles-news)
**** Form: post /articles-news
***** Field: searchword (text)
***** Button: Go
**** Form: post /articles-news
***** Field: username (text)
***** Field: password (password)
***** Field: remember (checkbox)
***** Field: Submit (submit)
***** Field: Submit (submit)
***** Button: Log in
***** Button: Sign up / i’m New
**** Articles and News - 340B Price Guide (/articles-news)
***** Form: post /articles-news
****** Field: searchword (text)
****** Button: Go
***** Form: post /articles-news
****** Field: username (text)
****** Field: password (password)
****** Field: remember (checkbox)
****** Field: Submit (submit)
****** Field: Submit (submit)
****** Button: Log in
****** Button: Sign up / i’m New
***** Weekly Update Episode 1: President Trump Healthcare Executive Order - 340B Price Guide (/articles-news/133-weekly-update-episode-1-president-trump-healthcare-executive-order)
****** Home - 340B Price Guide (/)
******* Form: post /
******** Field: searchword (text)
******** Button: Go
******* Form: post /
******** Field: username (text)
******** Field: password (password)
******** Field: remember (checkbox)
******** Field: Submit (submit)
******** Field: Submit (submit)
******** Button: Log in
******** Button: Sign up / i’m New
******* Form: GET 
******** Field: searchword (text)
******** Button: FIND 340B PRICES
******* Articles and News - 340B Price Guide (/index.php/articles-news)
******** Form: post /articles-news
********* Field: searchword (text)
********* Button: Go
******** Form: post /articles-news
********* Field: username (text)
********* Field: password (password)
********* Field: remember (checkbox)
********* Field: Submit (submit)
********* Field: Submit (submit)
********* Button: Log in
********* Button: Sign up / i’m New
******** Articles and News - 340B Price Guide (/articles-news)
********* Form: post /articles-news
********** Field: searchword (text)
********** Button: Go
********* Form: post /articles-news
********** Field: username (text)
********** Field: password (password)
********** Field: remember (checkbox)
********** Field: Submit (submit)
********** Field: Submit (submit)
********** Button: Log in
********** Button: Sign up / i’m New
********* Novo Nordisk will discontinue Levemir - 340B Price Guide (/articles-news/118-novo-nordisk-will-discontinue-levemir)
********* What is 340B? - 340B Price Guide (/articles-news/50-what-is-340b)
********* Medications to Treat Obesity: What is Available? - 340B Price Guide (/articles-news/70-medications-to-treat-obesity-what-is-available)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********* Medications to Treat Obesity: What is Available? - 340B Price Guide (/articles-news/70-medications-to-treat-obesity-what-is-available)
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
******** Articles and News - 340B Price Guide (/articles-news)
********* Form: post /articles-news
********** Field: searchword (text)
********** Button: Go
********* Form: post /articles-news
********** Field: username (text)
********** Field: password (password)
********** Field: remember (checkbox)
********** Field: Submit (submit)
********** Field: Submit (submit)
********** Button: Log in
********** Button: Sign up / i’m New
********* 340B Registration Periods - 340B Price Guide (/articles-news/13-340b-registration-period)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********* 340B Registration Periods - 340B Price Guide (/articles-news/13-340b-registration-period)
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
******** Articles and News - 340B Price Guide (/articles-news)
********* Form: post /articles-news
********** Field: searchword (text)
********** Button: Go
********* Form: post /articles-news
********** Field: username (text)
********** Field: password (password)
********** Field: remember (checkbox)
********** Field: Submit (submit)
********** Field: Submit (submit)
********** Button: Log in
********** Button: Sign up / i’m New
********* Mobile App - How to Use - 340B Price Guide (/articles-news/132-mobile-app-how-to-use)
********* Weekly Update Episode 1: President Trump Healthcare Executive Order - 340B Price Guide (/articles-news/133-weekly-update-episode-1-president-trump-healthcare-executive-order)
********* Rite Aid halts dispensing GLP1 agonists (Ozempic/Trulicity/Victoza) - 340B Price Guide (/articles-news/134-rite-aid-is-halts-dispensing-glp1-agonists-ozempic-trulicity-victoza)
********* Continued Brand Name Victoza Shortages - 340B Price Guide (/articles-news/138-continued-brand-name-victoza-shortages)
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
******** Articles and News - 340B Price Guide (/articles-news)
********* Form: post /articles-news
********** Field: searchword (text)
********** Button: Go
********* Form: post /articles-news
********** Field: username (text)
********** Field: password (password)
********** Field: remember (checkbox)
********** Field: Submit (submit)
********** Field: Submit (submit)
********** Button: Log in
********** Button: Sign up / i’m New
********* Eli Lilly Forced To Remove Restrictions - 340B Price Guide (/articles-news/119-eli-lilly-forced-to-remove-restrictions)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********** Eli Lilly Forced To Remove Restrictions - 340B Price Guide (/articles-news/119-eli-lilly-forced-to-remove-restrictions)
********** 340B Price Guide (/component/mailto/)
*********** Form: post /component/mailto/?task=send
************ Field: emailto (email)
************ Field: sender (text)
************ Field: emailfrom (email)
************ Field: subject (text)
************ Field: g-recaptcha-response (text)
************ Button: Send
************ Button: Cancel
********* Rite Aid Corp. Announces Closure of Oregon Pharmacies - 340B Price Guide (/articles-news/120-rite-aid-corp-announces-closure-of-oregon-pharmacies)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********** Rite Aid Corp. Announces Closure of Oregon Pharmacies - 340B Price Guide (/articles-news/120-rite-aid-corp-announces-closure-of-oregon-pharmacies)
********** 340B Price Guide (/component/mailto/)
*********** Form: post /component/mailto/?task=send
************ Field: emailto (email)
************ Field: sender (text)
************ Field: emailfrom (email)
************ Field: subject (text)
************ Field: g-recaptcha-response (text)
************ Button: Send
************ Button: Cancel
********* GSK to Discontinue Branded Flovent - 340B Price Guide (/articles-news/121-gsk-to-discontinue-branded-flovent)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********** GSK to Discontinue Branded Flovent - 340B Price Guide (/articles-news/121-gsk-to-discontinue-branded-flovent)
********** 340B Price Guide (/component/mailto/)
*********** Form: post /component/mailto/?task=send
************ Field: emailto (email)
************ Field: sender (text)
************ Field: emailfrom (email)
************ Field: subject (text)
************ Field: g-recaptcha-response (text)
************ Button: Send
************ Button: Cancel
********* Health Centers Move to Dismiss Challenge to Contract Pharmacy Law - 340B Price Guide (/articles-news/123-health-centers-move-to-dismiss-challenge-to-contract-pharmacy-law)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********** Health Centers Move to Dismiss Challenge to Contract Pharmacy Law - 340B Price Guide (/articles-news/123-health-centers-move-to-dismiss-challenge-to-contract-pharmacy-law)
********** 340B Price Guide (/component/mailto/)
*********** Form: post /component/mailto/?task=send
************ Field: emailto (email)
************ Field: sender (text)
************ Field: emailfrom (email)
************ Field: subject (text)
************ Field: g-recaptcha-response (text)
************ Button: Send
************ Button: Cancel
********* Basaglar no longer covered through Pacific Source and Trillium. - 340B Price Guide (/articles-news/125-basaglar-no-longer-be-covered-through-pacific-source)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********* Basaglar no longer covered through Pacific Source and Trillium. - 340B Price Guide (/articles-news/125-basaglar-no-longer-be-covered-through-pacific-source)
********* Ongoing Shortages of Diabetes Medication - 340B Price Guide (/articles-news/127-ongoing-shortages-of-diabetes-medication)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********* Ongoing Shortages of Diabetes Medication - 340B Price Guide (/articles-news/127-ongoing-shortages-of-diabetes-medication)
********* Getting Started - 340B Price Guide - 340B Price Guide (/articles-news/128-getting-started-340b-price-guide)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********* Getting Started - 340B Price Guide - 340B Price Guide (/articles-news/128-getting-started-340b-price-guide)
********* 2024 340B Oversight Hearing - 340B Price Guide (/articles-news/130-340b-oversight-hearing)
********** Form: post /articles-news
*********** Field: searchword (text)
*********** Button: Go
********** Form: post /articles-news
*********** Field: username (text)
*********** Field: password (password)
*********** Field: remember (checkbox)
*********** Field: Submit (submit)
*********** Field: Submit (submit)
*********** Button: Log in
*********** Button: Sign up / i’m New
********* 2024 340B Oversight Hearing - 340B Price Guide (/articles-news/130-340b-oversight-hearing)
********** http://www.340bpriceguide.net/media/webinars/20240604_Hearing_Oversight_Of_340B_Drug_Pricing_Program-Full_Audio.m4a (/media/webinars/20240604_Hearing_Oversight_Of_340B_Drug_Pricing_Program-Full_Audio.m4a)
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
********* 340B Price Guide (/component/mailto/)
********** Form: post /component/mailto/?task=send
*********** Field: emailto (email)
*********** Field: sender (text)
*********** Field: emailfrom (email)
*********** Field: subject (text)
*********** Field: g-recaptcha-response (text)
*********** Button: Send
*********** Button: Cancel
******** 340B Price Guide (/component/mailto/)
********* Form: post /component/mailto/?task=send
********** Field: emailto (email)
********** Field: sender (text)
********** Field: emailfrom (email)
********** Field: subject (text)
********** Field: g-recaptcha-response (text)
********** Button: Send
********** Button: Cancel
******** 340B Price Guide (/component/mailto/)
********* Form: post /component/mailto/?task=send
********** Field: emailto (email)
********** Field: sender (text)
********** Field: emailfrom (email)
********** Field: subject (text)
********** Field: g-recaptcha-response (text)
********** Button: Send
********** Button: Cancel
******** 340B Price Guide (/component/mailto/)
********* Form: post /component/mailto/?task=send
********** Field: emailto (email)
********** Field: sender (text)
********** Field: emailfrom (email)
********** Field: subject (text)
********** Field: g-recaptcha-response (text)
********** Button: Send
********** Button: Cancel
******** 340B Price Guide (/component/mailto/)
********* Form: post /component/mailto/?task=send
********** Field: emailto (email)
********** Field: sender (text)
********** Field: emailfrom (email)
********** Field: subject (text)
********** Field: g-recaptcha-response (text)
********** Button: Send
********** Button: Cancel
******* Contact Us - 340B Price Guide (/index.php/contact-us)
******** Form: post /contact-us
********* Field: searchword (text)
********* Button: Go
******** Form: post /contact-us
********* Field: username (text)
********* Field: password (password)
********* Field: remember (checkbox)
********* Field: Submit (submit)
********* Field: Submit (submit)
********* Button: Log in
********* Button: Sign up / i’m New
******** Form: post 
********* Field: name (text)
********* Field: email (text)
********* Field: company (text)
********* Field: address (text)
********* Field: city (text)
********* Field: phone (text)
********* Field: inquiry_type (text)
********* Field: question (text)
********* Field: g-recaptcha-response (text)
********* Field: submit (submit)
********* Button: Submit
******** 340B Price Guide (/component/mailto/)
********* Form: post /component/mailto/?task=send
********** Field: emailto (email)
********** Field: sender (text)
********** Field: emailfrom (email)
********** Field: subject (text)
********** Field: g-recaptcha-response (text)
********** Button: Send
********** Button: Cancel
******** Contact Us - 340B Price Guide (/contact-us)
********* Form: post 
********** Field: name (text)
********** Field: email (text)
********** Field: company (text)
********** Field: address (text)
********** Field: city (text)
********** Field: phone (text)
********** Field: inquiry_type (text)
********** Field: question (text)
********** Field: g-recaptcha-response (text)
********** Field: submit (submit)
********** Button: Submit
***** Rite Aid halts dispensing GLP1 agonists (Ozempic/Trulicity/Victoza) - 340B Price Guide (/articles-news/134-rite-aid-is-halts-dispensing-glp1-agonists-ozempic-trulicity-victoza)
***** Continued Brand Name Victoza Shortages - 340B Price Guide (/articles-news/138-continued-brand-name-victoza-shortages)
***** 340B Price Guide (/component/mailto/)
****** Form: post /component/mailto/?task=send
******* Field: emailto (email)
******* Field: sender (text)
******* Field: emailfrom (email)
******* Field: subject (text)
******* Field: g-recaptcha-response (text)
******* Button: Send
******* Button: Cancel
***** 340B Price Guide (/component/mailto/)
****** Form: post /component/mailto/?task=send
******* Field: emailto (email)
******* Field: sender (text)
******* Field: emailfrom (email)
******* Field: subject (text)
******* Field: g-recaptcha-response (text)
******* Button: Send
******* Button: Cancel
***** 340B Price Guide (/component/mailto/)
****** Form: post /component/mailto/?task=send
******* Field: emailto (email)
******* Field: sender (text)
******* Field: emailfrom (email)
******* Field: subject (text)
******* Field: g-recaptcha-response (text)
******* Button: Send
******* Button: Cancel
***** 340B Price Guide (/component/mailto/)
****** Form: post /component/mailto/?task=send
******* Field: emailto (email)
******* Field: sender (text)
******* Field: emailfrom (email)
******* Field: subject (text)
******* Field: g-recaptcha-response (text)
******* Button: Send
******* Button: Cancel
**** Articles and News - 340B Price Guide (/articles-news)
***** Form: post /articles-news
****** Field: searchword (text)
****** Button: Go
***** Form: post /articles-news
****** Field: username (text)
****** Field: password (password)
****** Field: remember (checkbox)
****** Field: Submit (submit)
****** Field: Submit (submit)
****** Button: Log in
****** Button: Sign up / i’m New
***** Eli Lilly Forced To Remove Restrictions - 340B Price Guide (/articles-news/119-eli-lilly-forced-to-remove-restrictions)
****** Form: post /articles-news
******* Field: searchword (text)
******* Button: Go
****** Form: post /articles-news
******* Field: username (text)
******* Field: password (password)
******* Field: remember (checkbox)
******* Field: Submit (submit)
******* Field: Submit (submit)
******* Button: Log in
******* Button: Sign up / i’m New
****** Eli Lilly Forced To Remove Restrictions - 340B Price Guide (/articles-news/119-eli-lilly-forced-to-remove-restrictions)
****** 340B Price Guide (/component/mailto/)
******* Form: post /component/mailto/?task=send
******** Field: emailto (email)
******** Field: sender (text)
******** Field: emailfrom (email)
******** Field: subject (text)
******** Field: g-recaptcha-response (text)
******** Button: Send
******** Button: Cancel
***** Rite Aid Corp. Announces Closure of Oregon Pharmacies - 340B Price Guide (/articles-news/120-rite-aid-corp-announces-closure-of-oregon-pharmacies)
****** Form: post /articles-news
******* Field: searchword (text)
******* Button: Go
****** Form: post /articles-news
******* Field: username (text)
******* Field: password (password)
******* Field: remember (checkbox)
******* Field: Submit (submit)
******* Field: Submit (submit)
******* Button: Log in
******* Button: Sign up / i’m New
****** Rite Aid Corp. Announces Closure of Oregon Pharmacies - 340B Price Guide (/articles-news/120-rite-aid-corp-announces-closure-of-oregon-pharmacies)
****** 340B Price Guide (/component/mailto/)
******* Form: post /component/mailto/?task=send
******** Field: emailto (email)
******** Field: sender (text)
******** Field: emailfrom (email)
******** Field: subject (text)
******** Field: g-recaptcha-response (text)
******** Button: Send
******** Button: Cancel
***** GSK to Discontinue Branded Flovent - 340B Price Guide (/articles-news/121-gsk-to-discontinue-branded-flovent)
****** Form: post /articles-news
******* Field: searchword (text)
******* Button: Go
****** Form: post /articles-news
******* Field: username (text)
******* Field: password (password)
******* Field: remember (checkbox)
******* Field: Submit (submit)
******* Field: Submit (submit)
******* Button: Log in
******* Button: Sign up / i’m New
****** GSK to Discontinue Branded Flovent - 340B Price Guide (/articles-news/121-gsk-to-discontinue-branded-flovent)
****** 340B Price Guide (/component/mailto/)
******* Form: post /component/mailto/?task=send
******** Field: emailto (email)
******** Field: sender (text)
******** Field: emailfrom (email)
******** Field: subject (text)
******** Field: g-recaptcha-response (text)
******** Button: Send
******** Button: Cancel
***** Health Centers Move to Dismiss Challenge to Contract Pharmacy Law - 340B Price Guide (/articles-news/123-health-centers-move-to-dismiss-challenge-to-contract-pharmacy-law)
****** Form: post /articles-news
******* Field: searchword (text)
******* Button: Go
****** Form: post /articles-news
******* Field: username (text)
******* Field: password (password)
******* Field: remember (checkbox)
******* Field: Submit (submit)
******* Field: Submit (submit)
******* Button: Log in
******* Button: Sign up / i’m New
****** Health Centers Move to Dismiss Challenge to Contract Pharmacy Law - 340B Price Guide (/articles-news/123-health-centers-move-to-dismiss-challenge-to-contract-pharmacy-law)
****** 340B Price Guide (/component/mailto/)
******* Form: post /component/mailto/?task=send
******** Field: emailto (email)
******** Field: sender (text)
******** Field: emailfrom (email)
******** Field: subject (text)
******** Field: g-recaptcha-response (text)
******** Button: Send
******** Button: Cancel
***** Basaglar no longer covered through Pacific Source and Trillium. - 340B Price Guide (/articles-news/125-basaglar-no-longer-be-covered-through-pacific-source)
****** Form: post /articles-news
******* Field: searchword (text)
******* Button: Go
****** Form: post /articles-news
******* Field: username (text)
******* Field: password (password)
******* Field: remember (checkbox)
******* Field: Submit (submit)
******* Field: Submit (submit)
******* Button: Log in
******* Button: Sign up / i’m New
***** Basaglar no longer covered through Pacific Source and Trillium. - 340B Price Guide (/articles-news/125-basaglar-no-longer-be-covered-through-pacific-source)
***** Ongoing Shortages of Diabetes Medication - 340B Price Guide (/articles-news/127-ongoing-shortages-of-diabetes-medication)
****** Form: post /articles-news
******* Field: searchword (text)
******* Button: Go
****** Form: post /articles-news
******* Field: username (text)
******* Field: password (password)
******* Field: remember (checkbox)
******* Field: Submit (submit)
******* Field: Submit (submit)
******* Button: Log in
******* Button: Sign up / i’m New
***** Ongoing Shortages of Diabetes Medication - 340B Price Guide (/articles-news/127-ongoing-shortages-of-diabetes-medication)
***** Getting Started - 340B Price Guide - 340B Price Guide (/articles-news/128-getting-started-340b-price-guide)
****** Form: post /articles-news
******* Field: searchword (text)
******* Button: Go
****** Form: post /articles-news
******* Field: username (text)
******* Field: password (password)
******* Field: remember (checkbox)
******* Field: Submit (submit)
******* Field: Submit (submit)
******* Button: Log in
******* Button: Sign up / i’m New
***** Getting Started - 340B Price Guide - 340B Price Guide (/articles-news/128-getting-started-340b-price-guide)
***** 2024 340B Oversight Hearing - 340B Price Guide (/articles-news/130-340b-oversight-hearing)
****** Form: post /articles-news
******* Field: searchword (text)
******* Button: Go
****** Form: post /articles-news
******* Field: username (text)
******* Field: password (password)
******* Field: remember (checkbox)
******* Field: Submit (submit)
******* Field: Submit (submit)
******* Button: Log in
******* Button: Sign up / i’m New
***** 2024 340B Oversight Hearing - 340B Price Guide (/articles-news/130-340b-oversight-hearing)
****** https://www.340bpriceguide.net/media/webinars/20240604_Hearing_Oversight_Of_340B_Drug_Pricing_Program-Full_Audio.m4a (/media/webinars/20240604_Hearing_Oversight_Of_340B_Drug_Pricing_Program-Full_Audio.m4a)
***** 340B Price Guide (/component/mailto/)
****** Form: post /component/mailto/?task=send
******* Field: emailto (email)
******* Field: sender (text)
******* Field: emailfrom (email)
******* Field: subject (text)
******* Field: g-recaptcha-response (text)
******* Button: Send
******* Button: Cancel
***** 340B Price Guide (/component/mailto/)
****** Form: post /component/mailto/?task=send
******* Field: emailto (email)
******* Field: sender (text)
******* Field: emailfrom (email)
******* Field: subject (text)
******* Field: g-recaptcha-response (text)
******* Button: Send
******* Button: Cancel
***** 340B Price Guide (/component/mailto/)
****** Form: post /component/mailto/?task=send
******* Field: emailto (email)
******* Field: sender (text)
******* Field: emailfrom (email)
******* Field: subject (text)
******* Field: g-recaptcha-response (text)
******* Button: Send
******* Button: Cancel
***** 340B Price Guide (/component/mailto/)
****** Form: post /component/mailto/?task=send
******* Field: emailto (email)
******* Field: sender (text)
******* Field: emailfrom (email)
******* Field: subject (text)
******* Field: g-recaptcha-response (text)
******* Button: Send
******* Button: Cancel
**** 340B Price Guide (/component/mailto/)
***** Form: post /component/mailto/?task=send
****** Field: emailto (email)
****** Field: sender (text)
****** Field: emailfrom (email)
****** Field: subject (text)
****** Field: g-recaptcha-response (text)
****** Button: Send
****** Button: Cancel
**** 340B Price Guide (/component/mailto/)
***** Form: post /component/mailto/?task=send
****** Field: emailto (email)
****** Field: sender (text)
****** Field: emailfrom (email)
****** Field: subject (text)
****** Field: g-recaptcha-response (text)
****** Button: Send
****** Button: Cancel
**** 340B Price Guide (/component/mailto/)
***** Form: post /component/mailto/?task=send
****** Field: emailto (email)
****** Field: sender (text)
****** Field: emailfrom (email)
****** Field: subject (text)
****** Field: g-recaptcha-response (text)
****** Button: Send
****** Button: Cancel
**** 340B Price Guide (/component/mailto/)
***** Form: post /component/mailto/?task=send
****** Field: emailto (email)
****** Field: sender (text)
****** Field: emailfrom (email)
****** Field: subject (text)
****** Field: g-recaptcha-response (text)
****** Button: Send
****** Button: Cancel
*** Contact Us - 340B Price Guide (/index.php/contact-us)
**** Form: post /contact-us
***** Field: searchword (text)
***** Button: Go
**** Form: post /contact-us
***** Field: username (text)
***** Field: password (password)
***** Field: remember (checkbox)
***** Field: Submit (submit)
***** Field: Submit (submit)
***** Button: Log in
***** Button: Sign up / i’m New
**** Form: post 
***** Field: name (text)
***** Field: email (text)
***** Field: company (text)
***** Field: address (text)
***** Field: city (text)
***** Field: phone (text)
***** Field: inquiry_type (text)
***** Field: question (text)
***** Field: g-recaptcha-response (text)
***** Field: submit (submit)
***** Button: Submit
**** 340B Price Guide (/component/mailto/)
***** Form: post /component/mailto/?task=send
****** Field: emailto (email)
****** Field: sender (text)
****** Field: emailfrom (email)
****** Field: subject (text)
****** Field: g-recaptcha-response (text)
****** Button: Send
****** Button: Cancel
**** Contact Us - 340B Price Guide (/contact-us)
***** Form: post 
****** Field: name (text)
****** Field: email (text)
****** Field: company (text)
****** Field: address (text)
****** Field: city (text)
****** Field: phone (text)
****** Field: inquiry_type (text)
****** Field: question (text)
****** Field: g-recaptcha-response (text)
****** Field: submit (submit)
****** Button: Submit
@endmindmap